### ISSUE TITLE
Failed to configure policies for 'customized_snat'

### ISSUE THREAD

**Issue by patelavtx** [terraform-aviatrix-modules/terraform-aviatrix-mc-overlap-nat-spoke#4]
# Module version 1.0.4 - 

1. When applying/modifying NAT on **single spoke g/w** (i.e. non HA) the following error is seen (see attached screenshot below)

2. Modifying module local variable in variables.tf  addresses the issue/error:

**FROM:**

_locals {
  is_ha = var.spoke_gw_object.ha_gw_size != null
}_

**TO:**

locals {
  is_ha = var.spoke_gw_object.ha_gw_size != ""
}

![custom_snatIssue](https://user-images.githubusercontent.com/93542155/175775360-4d5eeb84-9a69-4afc-b889-f2ed34c2a377.PNG)

**Comment by Dennizz** [comment]
Fix has been merged. Needs testing and validation before releasing a new version and closing the issue.

**Comment by patelavtx** [comment]
Adding only this line resolved the above error (module version 1.0.4)

locals {
is_ha = var.spoke_gw_object.ha_gw_size != ""
}

The following resulted in same error:

is_ha = var.spoke_gw_object.ha_gw_size != null || var.spoke_gw_object.ha_gw_size != ""
or
is_ha = var.spoke_gw_object.ha_gw_size != "" || var.spoke_gw_object.ha_gw_size != null

**Comment by Dennizz** [comment]
Addressed in 1.0.6
