### ISSUE TITLE
Unsupported argument  under resource block 'aviatrix_gateway_dnat"

### ISSUE THREAD

**Issue by patelavtx** [terraform-aviatrix-modules/terraform-aviatrix-mc-overlap-nat-spoke#6]
Module version 1.0.4
+ Following error is seen for the dnat rules  versions 1.03 - 1.0.1 had this entry and can't recall seeing this:

![image](https://user-images.githubusercontent.com/93542155/216688672-fd80454b-3c14-4e3e-9074-1454cc84634a.png)

The issue is overcome (and module deploys fine) by commenting this 'sync_to_ha' out  under the 'aviatrix_gateway_dnat' resource block.

**Comment by Dennizz** [comment]
Solved in v1.1.0
